### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by brettz9** [DonaldDerek/PiR.tv#8]
Hi,

Was just wondering if you might consider a name change for the project? I think it would put more people at ease if it weren't thought that the content was being obtained illegally or such. I know "Google TV" is not possible, but what about something like "Open TV" or "Pi TV" or something like that?

**Comment by DonaldDerek** [comment]
Thank you Brettz, 

Pirate TV is open source, you're free to fork the project and call it whatever you'd like!
